# Linear Algebra

## Creating Vectors and Matrices
We will be making use of some special python modules in the notebook to create and process vectors and matrices. Majorly numpy and pandas will be used to represent matrices and vectors.

### Importing the numpy module
This gives you the ability to create arrays and process them in python

In [1]:
import numpy as np

### Creating Arrays from Lists

In [5]:
# list
li = [1, 2, 3]

# array
array = np.array(li)

# display array
print(array)

[1 2 3]


### Jupyter has a print-ish nature
when a varible is expressed in a cell as the last statement, jupyter prints it

In [8]:
array

array([1, 2, 3])

### A Matrix List

In [9]:
# list of list
li_li = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#matrix as array
matrix = np.array(li_li)

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.array takes other parameters
There are other parameters that the np.array method takes and '<b>dtype</b>' is one of them. It is used to set the type of data in the numpy array

In [11]:
# as 8-bits integer
array = np.array(li, dtype=np.int8)

array

array([1, 2, 3], dtype=int8)

In [13]:
# as 16-bits float
array = np.array(li, dtype=np.float16)

array

array([1., 2., 3.], dtype=float16)

In [14]:
# as 16-bits float
matrix = np.array(li_li, dtype=np.float16)

matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)

### Creating Arrays from Nothing

In [16]:
# 3 by 3 filled with zeros
array = np.zeros((3, 3), dtype=np.int8)

array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [19]:
# 3 by 3 filled with ones
array = np.ones((3, 3), dtype=np.float16)

array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [21]:
# from random distributions
array = np.random.randint(255, size=(3, 3))

array

array([[218, 107, 167],
       [ 23, 126,  19],
       [ 35, 135, 102]])

### Creating Arrays from 'not exactly' Nothing

In [25]:
# array filled with 255
array = np.full((3, 3), 255)

array

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]])

### Convert Matrix to Vector

In [28]:
# view matrix as it was before
print('Matrix as it was before\n================\n', matrix, '\n')

# make matrix to vector
matrix_as_vector = matrix.flatten()

# display vector
print('vector =', matrix_as_vector)

Matrix as it was before
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

vector = [1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Vector (and Matrix) Operations
Addition, subtraction, scalar multiplication, element-wise multiplication, dot product, matrix multiplication

In [69]:
# initialize two vectors vector_A and vector_B
vector_A = np.array([1, 2, 3])
vector_B = np.array([1, 4, 7])

In [70]:
vector_A

array([1, 2, 3])

In [71]:
vector_B

array([1, 4, 7])

In [77]:
matrix_A = np.random.randint(20, size=(3, 3))
matrix_B = np.random.randint(20, size=(3, 3))

In [78]:
matrix_A

array([[10,  4, 14],
       [ 9,  4,  3],
       [19,  2,  5]])

In [79]:
matrix_B

array([[ 8,  0,  5],
       [19, 14, 18],
       [ 3, 15,  9]])

### Vector (and Matrix) vector_Addition

In [80]:
vector_A + vector_B

array([ 2,  6, 10])

In [81]:
matrix_A + matrix_B

array([[18,  4, 19],
       [28, 18, 21],
       [22, 17, 14]])

### Vector (and Matrix) Subtraction

In [82]:
vector_B - vector_A

array([0, 2, 4])

In [86]:
matrix_B - matrix_A

array([[ -2,  -4,  -9],
       [ 10,  10,  15],
       [-16,  13,   4]])

### Vector (and Matrix) Scalar-Multiplication

In [87]:
2 * vector_A

array([2, 4, 6])

In [88]:
2 * matrix_A

array([[20,  8, 28],
       [18,  8,  6],
       [38,  4, 10]])

### Vector (and Matrix) Element-Wise Multiplication

In [85]:
vector_B * vector_A

array([ 1,  8, 21])

In [89]:
matrix_A * matrix_B

array([[ 80,   0,  70],
       [171,  56,  54],
       [ 57,  30,  45]])

### Vector (and Matrix) Matrix-Multiplication

In [90]:
np.matmul(vector_A, vector_B)

30

In [91]:
np.matmul(matrix_A, matrix_B)

array([[198, 266, 248],
       [157, 101, 144],
       [205, 103, 176]])

### Vector (and Matrix) Dot Product

In [92]:
np.dot(vector_A, vector_B)

30

In [93]:
np.dot(matrix_A, matrix_B)

array([[198, 266, 248],
       [157, 101, 144],
       [205, 103, 176]])

### Determinants

In [97]:
np.linalg.det(vector_A)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [96]:
np.linalg.det(matrix_A)

-623.9999999999995

## Loading Datasets (CSV)
One major way data is gotten in the program is by loading it in from an external source. Various places can serve as a data source examples are SQL database, CSV files, EXCEL files, JSON files and so on.

In [29]:
# load using numpy
dataset = np.genfromtxt('FL_insurance_sample.csv', delimiter=',', dtype=None)

# display dataset
dataset

c:\program files\python37\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([[b'policyID', b'statecode', b'county', ..., b'line',
        b'construction', b'point_granularity'],
       [b'119736', b'FL', b'CLAY COUNTY', ..., b'Residential',
        b'Masonry', b'1'],
       [b'448094', b'FL', b'CLAY COUNTY', ..., b'Residential',
        b'Masonry', b'3'],
       ...,
       [b'791209', b'FL', b'PINELLAS COUNTY', ..., b'Residential',
        b'Wood', b'4'],
       [b'322627', b'FL', b'PINELLAS COUNTY', ..., b'Residential',
        b'Masonry', b'3'],
       [b'398149', b'FL', b'PINELLAS COUNTY', ..., b'Residential',
        b'Masonry', b'1']], dtype='|S19')

In [35]:
# load dataset
dataset = np.genfromtxt('FL_insurance_sample.csv', delimiter=',', dtype=np.float64)

# display
dataset

array([    nan, 119736., 448094., ..., 791209., 322627., 398149.])

### Dataset Size

In [36]:
dataset.shape

(36635, 18)

### Reading columns

In [38]:
# reading the first column of all the dataset
policyID = dataset[:, 0]

policyID

array([    nan, 119736., 448094., ..., 791209., 322627., 398149.])

## Computing Central Tendency
Central Tendency involves mean, median, mode and <a href='https://www.wikiwand.com/en/Central_tendency'>so on</a>

In [ ]:

create

dataset = np.genfromtxt('FL_insurance_sample.csv', delimiter=',')